source "$HOME/.environment_files/shortcuts/codeCalculadoraRetiro.shortcuts.sh"
source "$HOME/.environment_files/shortcuts/codeFLOKY.shortcuts.sh"
source "$HOME/.environment_files/shortcuts/codeFLOKYt.shortcuts.sh"
source "$HOME/.environment_files/shortcuts/codeMyKIA.shortcuts.sh"
source "$HOME/.environment_files/shortcuts/codePescadata.shortcuts.sh"